name: WerryMath

on:
  push:
    branches:
      - "master"


jobs:
  pre-release:
    name: "Pre Release"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8" ]
        os: ['windows-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - if: matrix.os == 'windows-latest'
        name: Windows Shortcut
        run: |
          python -m pip install pywin32
      - name: Build App
        run: |
          python build.py -y
      - uses: papeloto/action-zip@v1
        with:
          files: release/dist/WerryMath/
          dest: WerryMath-${{ matrix.os }}.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
           automatic_release_tag: "latest"
           prerelease: true
           title: "Development Build"
           files: |
             WerryMath-${{ matrix.os }}.zip

